# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

# Computer-generated files and other files which cannot be copyrighted
[[annotations]]
path = [
    ".ansible-lint",
    ".github/renovate.json",
    ".github/workflows/pre-commit.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".yamllint.yml",
    "meta/main.yml"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Apparently not parsed correctly for some reason …
[[annotations]]
path = ["templates/config.yaml.j2"]
SPDX-FileCopyrightText = [
  "2023 Julian-Samuel Gebühr",
  "2023 - 2024 Nikita Chernyi"
]
SPDX-License-Identifier = "AGPL-3.0-or-later"

# See https://github.com/mother-of-all-self-hosting/ansible-role-backup_borg/issues/15
[[annotations]]
path = ["templates/sshkey.j2"]
SPDX-FileCopyrightText = [
  "2023 Julian-Samuel Gebühr"
]
SPDX-License-Identifier = "AGPL-3.0-or-later"
