# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev

# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform BorgBackup installation tasks
  tags:
    - setup-all
    - setup-backup-borg
    - install-all
    - install-backup-borg
  block:
    - name: Validate BorgBackup configuration
      when: backup_borg_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install BorgBackup
      when: backup_borg_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform BorgBackup uninstallation tasks
  tags:
    - setup-all
    - setup-backup-borg
  block:
    - name: Uninstall BorgBackup
      when: not backup_borg_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
