# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev

# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
      when: "backup_borg_enabled | bool"

    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
      when: "backup_borg_enabled | bool"
  tags:
    - setup-all
    - setup-backup-borg
    - install-all
    - install-backup-borg

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
      when: "not backup_borg_enabled | bool"
  tags:
    - setup-all
    - setup-backup-borg
