# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of BorgBackup systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_borg_identifier }}.service"
  register: backup_borg_service_stat

- name: Uninstall BorgBackup systemd services and files
  when: backup_borg_service_stat.stat.exists | bool
  block:
    - name: Ensure BorgBackup systemd service is stopped
      ansible.builtin.service:
        name: "{{ backup_borg_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure BorgBackup systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_borg_identifier }}.service"
        state: absent

    - name: Ensure BorgBackup timer does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_borg_identifier }}.timer"
        state: absent

    - name: Ensure BorgBackup path does not exist
      ansible.builtin.file:
        path: "{{ backup_borg_base_path }}"
        state: absent
